### ISSUE TITLE
Re-rendering PR?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/django-redis-cache-feedstock#2]
Appears this hasn't been re-rendered in a very long time and there doesn't appear to be a recent re-rendering PR. While we can certainly re-render this manually, I would like to understand why this happened (or hasn't if you will) and fix it. Do you have any thoughts on this, @pelson?

**Comment by pelson** [comment]
Ping to https://github.com/conda-forge/conda-forge-webservices/issues/29. I'll try to fix shortly.
